ci: add check commits job
* ci: add check commits job

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: testing pipeline

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: testing

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: relates to #121 commit checks

added ability to check the latest commit on push. this
allows for developer to get quick feedback on a bad
commit message and adjust it prior to the contxt of
a PR.  additionally, within a PR, a developer will
have all commits check prior to a final merge.

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: quick refactor prior to merge

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: add check commits job

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: testing pipeline

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: testing

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: relates to #121 commit checks

added ability to check the latest commit on push. this
allows for developer to get quick feedback on a bad
commit message and adjust it prior to the contxt of
a PR.  additionally, within a PR, a developer will
have all commits check prior to a final merge.

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: quick refactor prior to merge

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: added debugging

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* refactor: use get-pr-commits action with regex

Signed-off-by: Dustin Scott <sdustin@vmware.com>

* ci: remove debug logging

Signed-off-by: Dustin Scott <sdustin@vmware.com>

diff --git a/.github/workflows/check.yaml b/.github/workflows/check.yaml
--- a/.github/workflows/check.yaml
+++ b/.github/workflows/check.yaml
@@ -5,6 +5,54 @@ on:
   - pull_request
 
 jobs:
+  check-latest-commit:
+    name: Check Latest Commit Message
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
+      - name: Check Latest Commit Message
+        run: |
+          COMMIT_MSG=`git log -n 1 --pretty=format:"%s"`
+
+          if [[ ! "$COMMIT_MSG" =~ ^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_\/¯)(\(\w+\))?(!)?(: (.*\s*)*))|(Merge (.*\s*)*)|(Initial commit$) ]]; then
+              echo "commit message check failed:"
+              echo
+              echo "${COMMIT_MSG}"
+              echo
+              echo "message is not conventional commits format"
+              echo "please see https://www.conventionalcommits.org/en/v1.0.0/#specification"
+
+              exit 1
+          fi
+
+  check-commits:
+    name: Check Commit Messages
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
+      - name: Get PR Commits
+        id: get-pr-commits
+        uses: tim-actions/get-pr-commits@master
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check Commit Messages
+        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
+        with:
+          commits: ${{ steps.get-pr-commits.outputs.commits }}
+          pattern: '^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_\/¯)(\(\w+\))?(!)?(: (.*\s*)*))|(Merge (.*\s*)*)|(Initial commit$)(\n.*)*$'
+          error: |
+              commit message check failed:
+
+              message is not conventional commits format
+              please see https://www.conventionalcommits.org/en/v1.0.0/#specification
+
   dco-check:
     name: DCO Check
     if: github.event_name == 'pull_request'
